import{a as S,S as q,i}from"./assets/vendor-BAQQTdrx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const M="55731551-c8f9ff8e643af6b8c00d564fe",R="https://pixabay.com/api/";async function p(r,t){const s={key:M,q:encodeURIComponent(r),image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await S.get(R,{params:s})).data}const h=document.querySelector(".gallery"),d=document.querySelector(".load-more-btn"),u=document.querySelector(".loader"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:c,comments:w,downloads:P})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <div class="info-item"><b>Likes</b><span>${o}</span></div>
        <div class="info-item"><b>Views</b><span>${c}</span></div>
        <div class="info-item"><b>Comments</b><span>${w}</span></div>
        <div class="info-item"><b>Downloads</b><span>${P}</span></div>
      </div>
    </li>`).join("");h.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){h.innerHTML=""}function b(){u&&u.classList.remove("hidden")}function f(){u&&u.classList.add("hidden")}function v(){d&&d.classList.remove("hidden")}function m(){d&&d.classList.add("hidden")}const g=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let n=1,l="";const L=15;g.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements.query.value.trim(),!l){i.warning({message:"Please enter a search query",position:"topRight"});return}n=1,$(),m(),b();try{const t=await p(l,n);if(f(),t.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits);const s=Math.ceil(t.totalHits/L);n>=s?(m(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch{f(),i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g.reset()}});O.addEventListener("click",async()=>{n+=1,m(),b();try{const r=await p(l,n);f(),y(r.hits);const t=document.querySelector(".gallery-item");if(t){const a=t.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const s=Math.ceil(r.totalHits/L);n>=s?(m(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch{f(),i.error({message:"Failed to load more images.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
